FROM postgres:16@sha256:5a65324fe84dc41709ff914e90b07f3e2f577073ed27bf917d4873aca0c9ec51

RUN apt-get update && apt-get install -y \
    postgresql-16-pgvector \
    postgresql-16-rdkit \
    && rm -rf /var/lib/apt/lists/*

# The extensions need to be enabled in each database
# We can do this via a script in /docker-entrypoint-initdb.d/
COPY ./nestjs-backend/data/extensions.sql /docker-entrypoint-initdb.d/extensions.sql
