FROM postgres:16

RUN apt-get update && apt-get install -y \
    postgresql-16-pgvector \
    postgresql-16-rdkit \
    && rm -rf /var/lib/apt/lists/*

# The extensions need to be enabled in each database
# We can do this via a script in /docker-entrypoint-initdb.d/
COPY ./express-api/data/00_extensions.sql /docker-entrypoint-initdb.d/00_extensions.sql
